spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adaptive_testing
    password: postgres
    username: postgres
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

server:
  servlet:
    context-path: /api/v1

application:
  jwt:
    secret: #
    expiration-time: #
  refresh-token:
    expiration-time: #